name: Update Major Version Branch

on:
  release:
    types: [released]

permissions: {}

jobs:
  update-major-version-branch:
    permissions:
      contents: write
    runs-on: ubuntu-24.04-arm
    env:
      EARTHLY_CONVERSION_PARALLELISM: '5'
      EARTHLY_INSTALL_ID: 'earthbuild-actions-setup-githubactions'
    steps:
      - uses: EarthBuild/actions-setup@main
        with:
          version: v0.8.6
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref }}
      - name: Update Branch
        run: earth --ci -P --push +merge-release-to-major-branch --RELEASE_TAG="${{ github.ref }}"
